version: "3.4"
services:
  api:
    build:
      context: .
      target: release
    ports:
      - 5000:80
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=reader
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=library
    volumes:
      - ./db:/docker-entrypoint-initdb.d
